music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'


urlpatterns = [
    #/music/
    url(r'^$', views.index, name='index'),

    #/music/7232156/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name = 'detail'),

    # /music/7232156/favorite
    url(r"^(?P<album_id>[0-9]+)/favorite/$", views.favorite, name='favorite')

]

music/models.py
from __future__ import unicode_literals
from django.db import models

class Album(models.Model):
    album_title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    year = models.IntegerField(max_length=4)
    genre= models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    song_title = models.CharField(max_length=100)
    file_type= models.CharField(max_length=4)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from models import Album, Song
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.urlresolvers import reverse


def index(request):
    albums=Album.objects.all()
    context = {'albums': albums,}
    return render(request,'music/index.html',context)

def detail(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    '''
    try:
        album = Album.objects.get(id=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exist.")
    '''
    return render(request, 'music/detail.html', {'album': album})

def favorite(request, album_id):
    album = get_object_or_404(Album, id=album_id)

    try:
        selected_song = album.song_set.get(id=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message':'You did not select a valid song!'
    })
    else:
        if selected_song.is_favorite == True:
            selected_song.is_favorite = False
            selected_song.save()
        else:
            selected_song.is_favorite=True
            selected_song.save()
    return HttpResponseRedirect(reverse('music:detail', args=album_id))

music/templates/music/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">

<img src="{{ album.album_logo }}" height="300px">

<h1>Artist: {{ album.artist }}</h1>
<h2>Title: {{ album.album_title }}</h2>

{% if error_message %}
    <p><strong >{{ error_message }} </strong></p>
{% endif %}

{% if album.song_set.all %}
    <form action="{%  url 'music:favorite' album.id %}" method='post'>
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter}}" name="song" value="{{ song.id }}">
               <label for="song{{ forloop.counter}}">
               {{ song.song_title }}
               {% if song.is_favorite %}
                   <img src="http://cdn1.iconfinder.com/data/icons/icojoy/shadow/standart/png/24x24/001_15.png">
               {% endif %}
               </label><br>
   {% endfor %}
    <input type="submit" value="Favorite">
    </form>

{% else %}
<h3>No songs added yet</h3>
{% endif %}

music/templates/music/index.html
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.js"></script>
</head>

{% if albums %}
    <div class="ui link list">
        {% for album in albums %}
        <a class="item" href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
        {% endfor %}
    </div>
{% else %}
    <h3>THere are no albums yet</h3>
{% endif %}